#!/usr/bin/env python3
"""
================================================================================
CRIMSON ORBIT – MUSICAL BAND
Floppy Disk Image Builder (build_floppy.py)
Target Format: Standard 1.44 MB Floppy Disk Image (MusicalBand.flp)
Size: Exactly 1,474,560 bytes (2,880 sectors of 512 bytes)
================================================================================
"""

import os
import sys

FLOPPY_SIZE = 1474560  # 1.44 MB in bytes
SECTOR_SIZE = 512

def build_floppy():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.abspath(os.path.join(script_dir, ".."))
    builds_dir = os.path.join(project_root, "Builds")
    
    loader_path = os.path.join(builds_dir, "loader.bin")
    kernel_path = os.path.join(builds_dir, "kernel.bin")
    flp_path = os.path.join(builds_dir, "MusicalBand.flp")
    
    # Alternate names commonly generated by emu8086
    if not os.path.exists(loader_path):
        alt_loader = os.path.join(builds_dir, "boot.bin")
        if os.path.exists(alt_loader):
            loader_path = alt_loader

    print("=" * 60)
    print("   CRIMSON ORBIT :: FLOPPY DISK BUILDER")
    print("=" * 60)
    print(f"Project Directory : {project_root}")
    print(f"Builds Directory  : {builds_dir}")
    print(f"Target Floppy     : {flp_path}")
    print("-" * 60)

    # 1. Validate Loader Binary
    if not os.path.exists(loader_path):
        print(f"[!] Warning: Loader binary not found at:\n    {loader_path}")
        print("    Please compile 'Source/boot.asm' in emu8086 and save as 'Builds/loader.bin'.")
        return False

    with open(loader_path, "rb") as f:
        loader_data = bytearray(f.read())

    loader_len = len(loader_data)
    print(f"[*] Bootloader Size: {loader_len} bytes")

    if loader_len > SECTOR_SIZE:
        print(f"[ERROR] Bootloader exceeds sector size of 512 bytes ({loader_len} bytes)!")
        return False

    # Pad loader to 512 bytes if necessary
    if loader_len < SECTOR_SIZE:
        print(f"[*] Padding bootloader from {loader_len} bytes to 512 bytes...")
        loader_data.extend(b"\x00" * (SECTOR_SIZE - loader_len))

    # Ensure 55AAh boot signature at bytes 510-511
    if loader_data[510] != 0x55 or loader_data[511] != 0xAA:
        print("[*] Applying 0x55AA boot signature at bytes 510-511...")
        loader_data[510] = 0x55
        loader_data[511] = 0xAA

    # Save finalized 512-byte loader back to disk
    with open(loader_path, "wb") as f:
        f.write(loader_data)

    # 2. Validate Kernel Binary
    if not os.path.exists(kernel_path):
        print(f"[!] Warning: Kernel binary not found at:\n    {kernel_path}")
        print("    Please compile 'Source/kernel.asm' in emu8086 and save as 'Builds/kernel.bin'.")
        return False

    with open(kernel_path, "rb") as f:
        kernel_data = f.read()

    kernel_len = len(kernel_data)
    sectors_needed = (kernel_len + SECTOR_SIZE - 1) // SECTOR_SIZE
    print(f"[*] Kernel Size    : {kernel_len} bytes ({sectors_needed} sectors)")

    if sectors_needed > 36:
        print(f"[WARNING] Kernel size exceeds the 36 sectors (18 KB) loaded by boot.asm!")
        print(f"          Current sectors: {sectors_needed}. Bootloader loads: 36 sectors.")

    # 3. Assemble Floppy Disk Image
    floppy = bytearray(FLOPPY_SIZE)

    # Place boot sector at offset 0 (Sector 1)
    floppy[0:512] = loader_data

    # Place kernel at offset 512 (Sector 2 onwards)
    floppy[512 : 512 + kernel_len] = kernel_data

    # Write out MusicalBand.flp and aliases
    with open(flp_path, "wb") as f:
        f.write(floppy)

    for alias_name in ["CrimsonOrbit.flp", "CrimsonOrbit.img", "CrimsonOrbit_MusicalBand.flp"]:
        alias_path = os.path.join(builds_dir, alias_name)
        with open(alias_path, "wb") as f:
            f.write(floppy)

    print("-" * 60)
    print(f"[SUCCESS] Bootable floppy image successfully generated!")
    print(f"          File: {flp_path}")
    print(f"          Size: {len(floppy):,} bytes (Exact 1.44 MB standard)")
    print(f"          Boot Sector : Sector 1 (Bytes 0..511, Signature 0x55AA)")
    print(f"          Kernel      : Sectors 2..{sectors_needed + 1} (Bytes 512..{512 + kernel_len})")
    print("=" * 60)
    return True

if __name__ == "__main__":
    success = build_floppy()
    if not success:
        sys.exit(1)
